UNICODE_ENABLE= yes
EXTRAKEY_ENABLE = yes
SEND_STRING_ENABLE= yes
TAP_DANCE_ENABLE = yes
ENCODER_ENABLE = yes
VELOCIKEY_ENABLE = yes
RGBMATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812
RGBLIGHT_ENABLE = yes
RGB_LIGHT_DRIVER = WS2812

OLED_ENABLE = yes
OLED_DRIVER = SSD1306

WPM_ENABLE = yes
LTO_ENABLE = yes

BOOTLOADER = rp2040
CONVERT_TO = promicro_rp2040

