MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
RGBLIGHT_ENABLE = yes
ENCODER_ENABLE = yes
LTO_ENABLE = yes
OLED_ENABLE = yes
OLED_DRIVER = SSD1306
VELOCIKEY_ENABLE = yes
SEND_STRING_ENABLE = yes
TAP_DANCE_ENABLE = yes
WPM_ENABLE = yes

BOOTLOADER = rp2040
CONVERT_TO = promicro_rp2040
